#!/bin/bash

USER=jboss
POD_NAME=${1:-quarkus}
SOURCE_CODE=${2:-quarkus-demo}
DIR=$(dirname "$0")

rsync -avurP --blocking-io --rsync-path= --rsh="$(which kubectl) exec $POD_NAME -i -- " $DIR/$SOURCE_CODE rsync:/home/$USER/
