#!/bin/bash

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/*.jar /deployments/app.jar
