#!/bin/sh

mvn -f /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/pom.xml ${MAVEN_ARGS} package -DskipTests -DskipITs -Dmaven.repo.local=/tmp/artefacts && cp /usr/src/${CONTEXTPATH}/${MODULEDIRNAME}/target/${JARPATTERN}.jar /deployments/app.jar
