apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: prometheus.88.99.186.195.nip.io
      http:
        paths:
          - backend:
              serviceName: prometheus
              servicePort: 9090
            path: /prometheus
          - backend:
              serviceName: alertmanager-main
              servicePort: 9093
            path: /alertmanager