apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: example-jib-maven
spec:
  serviceAccountName: build-bot
  taskRef:
    name: jib-maven
  inputs:
    params:
      - name: DIRECTORY
        value: .
    resources:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/cmoulliard/rest-http-example.git
            - name: revision
              value: jib-logging
  outputs:
    resources:
      - name: image
        resourceRef:
          name: sb-image