apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: jib-maven
spec:
  inputs:
    params:
      - name: DIRECTORY
        description: The directory containing the app, relative to the source repository root
        default: .
      - name: CACHE
        description: The name of the volume for caching Maven artifacts and base image layers
        default: m2-sb
    resources:
      - name: source
        type: git
  outputs:
    resources:
      - name: image
        type: image

  steps:
    - name: build-and-push
      image: gcr.io/cloud-builders/mvn
      command:
        - mvn
        - compile
        - com.google.cloud.tools:jib-maven-plugin:2.0.0:build
        - -Duser.home=/builder/home
        - -Djib.from.image=registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
        - -Djib.allowInsecureRegistries=true
        - -Djib.from.auth.username=xxxxx
        - -Djib.from.auth.password=yyyyyy
        - -Dimage=$(outputs.resources.image.url)
      env:
      - name: "DOCKER_CONFIG"
        value: "/builder/home/.docker/"
      workingDir: /workspace/source/$(inputs.params.DIRECTORY)
      volumeMounts:
        - name: $(inputs.params.CACHE)
          mountPath: /builder/home/.m2
          subPath: m2-cache
        - name: $(inputs.params.CACHE)
          mountPath: /builder/home/.cache
          subPath: jib-cache

  volumes:
  - name: m2-sb
    persistentVolumeClaim:
      claimName: m2-sb